2014-04-23 09:11:22,612 ERROR - XMemcached network layout exception [net.rubyeye.xmemcached.impl.MemcachedHandler]
java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:33)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:69)
	at sun.nio.ch.IOUtil.write(IOUtil.java:40)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:336)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.doRealWrite(AbstractNioSession.java:323)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.writeToChannel(NioTCPSession.java:84)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:112)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:340)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchWriteEvent(SocketChannelController.java:67)
	at com.google.code.yanf4j.nio.impl.NioController.onWrite(NioController.java:168)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:283)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:22,614 ERROR - XMemcached network layout exception [net.rubyeye.xmemcached.impl.MemcachedHandler]
java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:33)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:69)
	at sun.nio.ch.IOUtil.write(IOUtil.java:40)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:336)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.doRealWrite(AbstractNioSession.java:323)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.writeToChannel(NioTCPSession.java:84)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:112)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:340)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchWriteEvent(SocketChannelController.java:67)
	at com.google.code.yanf4j.nio.impl.NioController.onWrite(NioController.java:168)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:283)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:22,614 ERROR - XMemcached network layout exception [net.rubyeye.xmemcached.impl.MemcachedHandler]
java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:33)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:69)
	at sun.nio.ch.IOUtil.write(IOUtil.java:40)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:336)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.doRealWrite(AbstractNioSession.java:323)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.writeToChannel(NioTCPSession.java:84)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:112)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:340)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchWriteEvent(SocketChannelController.java:67)
	at com.google.code.yanf4j.nio.impl.NioController.onWrite(NioController.java:168)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:283)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:22,654 ERROR - XMemcached network layout exception [net.rubyeye.xmemcached.impl.MemcachedHandler]
java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:33)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:69)
	at sun.nio.ch.IOUtil.write(IOUtil.java:40)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:336)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.doRealWrite(AbstractNioSession.java:323)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.writeToChannel(NioTCPSession.java:84)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:112)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.flush0(AbstractNioSession.java:284)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.closeChannel(NioTCPSession.java:314)
	at com.google.code.yanf4j.core.impl.AbstractSession.close(AbstractSession.java:286)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:165)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:340)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchWriteEvent(SocketChannelController.java:67)
	at com.google.code.yanf4j.nio.impl.NioController.onWrite(NioController.java:168)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:283)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:22,653 ERROR - XMemcached network layout exception [net.rubyeye.xmemcached.impl.MemcachedHandler]
java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:33)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:69)
	at sun.nio.ch.IOUtil.write(IOUtil.java:40)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:336)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.doRealWrite(AbstractNioSession.java:323)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.writeToChannel(NioTCPSession.java:84)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:112)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.flush0(AbstractNioSession.java:284)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.closeChannel(NioTCPSession.java:314)
	at com.google.code.yanf4j.core.impl.AbstractSession.close(AbstractSession.java:286)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:165)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:340)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchWriteEvent(SocketChannelController.java:67)
	at com.google.code.yanf4j.nio.impl.NioController.onWrite(NioController.java:168)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:283)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:22,654 ERROR - XMemcached network layout exception [net.rubyeye.xmemcached.impl.MemcachedHandler]
java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:33)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:69)
	at sun.nio.ch.IOUtil.write(IOUtil.java:40)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:336)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.doRealWrite(AbstractNioSession.java:323)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.writeToChannel(NioTCPSession.java:84)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:112)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.flush0(AbstractNioSession.java:284)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.closeChannel(NioTCPSession.java:314)
	at com.google.code.yanf4j.core.impl.AbstractSession.close(AbstractSession.java:286)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:165)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:340)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchWriteEvent(SocketChannelController.java:67)
	at com.google.code.yanf4j.nio.impl.NioController.onWrite(NioController.java:168)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:283)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:22,745 ERROR - XMemcached network layout exception [net.rubyeye.xmemcached.impl.MemcachedHandler]
java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:33)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:69)
	at sun.nio.ch.IOUtil.write(IOUtil.java:40)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:336)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.doRealWrite(AbstractNioSession.java:323)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.writeToChannel(NioTCPSession.java:84)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:112)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:340)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchWriteEvent(SocketChannelController.java:67)
	at com.google.code.yanf4j.nio.impl.NioController.onWrite(NioController.java:168)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:283)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:22,747 ERROR - XMemcached network layout exception [net.rubyeye.xmemcached.impl.MemcachedHandler]
java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:33)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:69)
	at sun.nio.ch.IOUtil.write(IOUtil.java:40)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:336)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.doRealWrite(AbstractNioSession.java:323)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.writeToChannel(NioTCPSession.java:84)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:112)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.flush0(AbstractNioSession.java:284)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.closeChannel(NioTCPSession.java:314)
	at com.google.code.yanf4j.core.impl.AbstractSession.close(AbstractSession.java:286)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:165)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:340)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchWriteEvent(SocketChannelController.java:67)
	at com.google.code.yanf4j.nio.impl.NioController.onWrite(NioController.java:168)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:283)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:22,751 ERROR - XMemcached network layout exception [net.rubyeye.xmemcached.impl.MemcachedHandler]
java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:33)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:69)
	at sun.nio.ch.IOUtil.write(IOUtil.java:40)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:336)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.doRealWrite(AbstractNioSession.java:323)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.writeToChannel(NioTCPSession.java:84)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:112)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:340)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchWriteEvent(SocketChannelController.java:67)
	at com.google.code.yanf4j.nio.impl.NioController.onWrite(NioController.java:168)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:283)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:22,752 ERROR - XMemcached network layout exception [net.rubyeye.xmemcached.impl.MemcachedHandler]
java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:33)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:69)
	at sun.nio.ch.IOUtil.write(IOUtil.java:40)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:336)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.doRealWrite(AbstractNioSession.java:323)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.writeToChannel(NioTCPSession.java:84)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:112)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.flush0(AbstractNioSession.java:284)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.closeChannel(NioTCPSession.java:314)
	at com.google.code.yanf4j.core.impl.AbstractSession.close(AbstractSession.java:286)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:165)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:340)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchWriteEvent(SocketChannelController.java:67)
	at com.google.code.yanf4j.nio.impl.NioController.onWrite(NioController.java:168)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:283)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:24,680 ERROR - Exception occured in controller [com.google.code.yanf4j.core.impl.AbstractController]
java.io.IOException: Connect to 122.224.171.132:11211 fail,No route to host: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:402)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:302)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:24,681 ERROR - Reactor dispatch events error [remoting]
java.io.IOException: Connect to 122.224.171.132:11211 fail,No route to host: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:402)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:302)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:24,680 ERROR - Reconnect to 122.224.171.132:11211 fail [com.google.code.yanf4j.core.impl.AbstractController]
2014-04-23 09:11:24,691 ERROR - Exception occured in controller [com.google.code.yanf4j.core.impl.AbstractController]
java.io.IOException: Connect to 122.224.171.132:11211 fail,No route to host: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:402)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:302)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:24,691 ERROR - Reconnect to 122.224.171.132:11211 fail [com.google.code.yanf4j.core.impl.AbstractController]
2014-04-23 09:11:24,691 ERROR - Reactor dispatch events error [remoting]
java.io.IOException: Connect to 122.224.171.132:11211 fail,No route to host: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:402)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:302)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:24,695 ERROR - Exception occured in controller [com.google.code.yanf4j.core.impl.AbstractController]
java.io.IOException: Connect to 122.224.171.132:11211 fail,No route to host: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:402)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:302)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:24,695 ERROR - Reconnect to 122.224.171.132:11211 fail [com.google.code.yanf4j.core.impl.AbstractController]
2014-04-23 09:11:24,695 ERROR - Reactor dispatch events error [remoting]
java.io.IOException: Connect to 122.224.171.132:11211 fail,No route to host: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:402)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:302)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:24,751 ERROR - Reconnect to 122.224.171.132:11211 fail [com.google.code.yanf4j.core.impl.AbstractController]
2014-04-23 09:11:24,751 ERROR - Exception occured in controller [com.google.code.yanf4j.core.impl.AbstractController]
java.io.IOException: Connect to 122.224.171.132:11211 fail,No route to host: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:402)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:302)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:24,751 ERROR - Reactor dispatch events error [remoting]
java.io.IOException: Connect to 122.224.171.132:11211 fail,No route to host: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:402)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:302)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:24,756 ERROR - Exception occured in controller [com.google.code.yanf4j.core.impl.AbstractController]
java.io.IOException: Connect to 122.224.171.132:11211 fail,No route to host: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:402)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:302)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:24,756 ERROR - Reactor dispatch events error [remoting]
java.io.IOException: Connect to 122.224.171.132:11211 fail,No route to host: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:402)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:302)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:141)
2014-04-23 09:11:24,756 ERROR - Reconnect to 122.224.171.132:11211 fail [com.google.code.yanf4j.core.impl.AbstractController]
2014-04-23 10:02:08,937 ERROR -  [DUBBO] Got unchecked and undeclared exception which called by 10.14.21.17. service: com.haiegoo.shopping.service.product.ProductService, method: getProductCount, exception: com.alibaba.dubbo.rpc.RpcException: 查询商品出错, dubbo version: 2.4.10, current host: 127.0.0.1 [com.alibaba.dubbo.rpc.filter.ExceptionFilter]
com.alibaba.dubbo.rpc.RpcException: 查询商品出错
	at com.haiegoo.shopping.service.product.impl.ProductServiceImpl.getProductCount(ProductServiceImpl.java:64)
	at com.alibaba.dubbo.common.bytecode.Wrapper2.invokeMethod(Wrapper2.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.AccessLogFilter.invoke(AccessLogFilter.java:199)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispather.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.ibatis.sqlmap.client.SqlMapException: There is no statement named product.getProductCount in this SqlMap.
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.getMappedStatement(SqlMapExecutorDelegate.java:231)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:509)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:493)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at org.springframework.orm.ibatis.SqlMapClientTemplate$1.doInSqlMapClient(SqlMapClientTemplate.java:270)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:200)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:268)
	at com.haiegoo.shopping.service.product.impl.ProductServiceImpl.getProductCount(ProductServiceImpl.java:60)
	... 29 more
2014-04-23 10:12:15,708 ERROR -  [DUBBO] Got unchecked and undeclared exception which called by 10.14.21.17. service: com.haiegoo.shopping.service.product.ProductService, method: getProductCount, exception: com.alibaba.dubbo.rpc.RpcException: 查询商品出错, dubbo version: 2.4.10, current host: 127.0.0.1 [com.alibaba.dubbo.rpc.filter.ExceptionFilter]
com.alibaba.dubbo.rpc.RpcException: 查询商品出错
	at com.haiegoo.shopping.service.product.impl.ProductServiceImpl.getProductCount(ProductServiceImpl.java:64)
	at com.alibaba.dubbo.common.bytecode.Wrapper2.invokeMethod(Wrapper2.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.AccessLogFilter.invoke(AccessLogFilter.java:199)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispather.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.springframework.jdbc.BadSqlGrammarException: SqlMapClient operation; bad SQL grammar []; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in com/haiegoo/shopping/dao/sqlmap/product.sqlmap.xml.  
--- The error occurred while applying a result map.  
--- Check the product.resultMap.  
--- Check the result mapping for the 'id' property.  
--- Cause: java.sql.SQLException: Column 'id' not found.
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:203)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:268)
	at com.haiegoo.shopping.service.product.impl.ProductServiceImpl.getProductCount(ProductServiceImpl.java:60)
	... 29 more
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in com/haiegoo/shopping/dao/sqlmap/product.sqlmap.xml.  
--- The error occurred while applying a result map.  
--- Check the product.resultMap.  
--- Check the result mapping for the 'id' property.  
--- Cause: java.sql.SQLException: Column 'id' not found.
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:201)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForObject(MappedStatement.java:120)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:518)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:493)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at org.springframework.orm.ibatis.SqlMapClientTemplate$1.doInSqlMapClient(SqlMapClientTemplate.java:270)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:200)
	... 31 more
Caused by: java.sql.SQLException: Column 'id' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1086)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1163)
	at com.mysql.jdbc.ResultSetImpl.getLong(ResultSetImpl.java:3055)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.ibatis.common.jdbc.logging.ResultSetLogProxy.invoke(ResultSetLogProxy.java:47)
	at com.sun.proxy.$Proxy14.getLong(Unknown Source)
	at com.ibatis.sqlmap.engine.type.LongTypeHandler.getResult(LongTypeHandler.java:35)
	at com.ibatis.sqlmap.engine.mapping.result.ResultMap.getPrimitiveResultMappingValue(ResultMap.java:619)
	at com.ibatis.sqlmap.engine.mapping.result.ResultMap.getResults(ResultMap.java:345)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.handleResults(SqlExecutor.java:384)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.handleMultipleResults(SqlExecutor.java:300)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:189)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
	... 37 more
